### ISSUE TITLE
Can't undo changes, there is no Regbackup file and more issues

### ISSUE THREAD

**Issue by Nyanrpg08** [UnLovedCookie/EchoX#1]
Hello, I have been having some issues regarding undoing the changes that EchoX made, specifically regarding finding the Regbackup file and trying to restore the system using the system restore point that EchoX makes before applying changes.

First off, yesterday (November 29th 2022) I tried to restore the system with the system restore point that EchoX made, since i didn't like how it activated XMouse, how it changed how the selection box on the desktop looked like, how the right-click menu with the dark mode it gives you a white border around the context menu, and etc... so I decided to go back in time and see if I could do something about it, I had to wait a whole night for the registry to be restored, so the next day, I turned on the pc, **and nothing changed**. Literally. So I decided to use the method that the program asked me to do, trying to find the Regbackup file and the bcdbackup.bcd file, although I found the bcdbackup.bcd file, there was no Regbackup file, I went on the C:\ directory to see if I could find it, but nothing, I tried to search my external hard drive, but nothing, all there that was there was the bcdbackup.bcd file, and some EchoX leftovers, here's an image: 
![Immagine 2022-11-30 160256](https://user-images.githubusercontent.com/80052499/204837044-d933f79a-d9dd-45d5-a460-4ba9d29072ff.png)

Please let me know as soon as you can how to fix this as i don't want to reinstall Windows as I have some important files on there.

**Comment by Nyanrpg08** [comment]
Also, one more thing, even if I tried to deactivate the XMouse tweak with Winaero Tweaker, every time i turn on my pc it will just activate by itself., no matter what i did.

**Comment by UnLovedCookie** [comment]
I don't know what you are referring to by xmouse but I'm guessing you're talking about the marc c mouse fix. It can be undone using the registry file inside the zip included.
[Windows_10+8.x_Default.zip](https://github.com/UnLovedCookie/EchoX/files/10345150/Windows_10%2B8.x_Default.zip)

**Comment by UnLovedCookie** [comment]
EchoX is no longer supported! For the latest updates, you can use CoutX.
